### ISSUE TITLE
Travis에서 s3로 build 파일 전송 시 에러

### ISSUE THREAD

**Issue by hanbee1005** [hanbee1005/springboot-aws#5]
# Skipping a deployment with the s3 provider because this branch is not permitted: main
main branch에 대한 허가가 없어서 배포를 스킵한다는 에러...

**Comment by hanbee1005** [comment]
```
deploy:
  - provider: s3
    ...
    on:
      branch: main
```

위와 같이 branch에 대한 설정 추가
